name: Verify Metadata

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: "18"

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@cbda684547adc8c052d50711417fa61b428a9f88 # v41
        with:
          files: |
            resources
            metadata.json

      - name: Build and verify
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm run build
          npm run generateMetadata

      - name: Check for any drift via git diff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git diff --no-ext-diff --exit-code metadata.json
