name: Verify Metadata

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            resources
            metadata.json

      - name: Build and verify
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm run build
          npm run generateMetadata

      - name: Check for any drift via git diff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git diff --no-ext-diff --exit-code metadata.json
